[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg"]

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd ../frontend && npm install"
]

[phases.build]
cmds = [
  "cd backend && npm run build",
  "cd ../frontend && npm run build"
]

[start]
cmd = "cd backend && npm start"

