[phases.setup]
nixPkgs = ["nodejs_20", "ffmpeg"]

[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "npm run build --prefix backend",
  "npm run build --prefix frontend"
]

[start]
cmd = "npm start --prefix backend"

